<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34" started-at="2018-02-12T23:51:32Z" finished-at="2018-02-12T23:51:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34" started-at="2018-02-12T23:51:32Z" finished-at="2018-02-12T23:51:33Z">
      <class name="testNGPractice.DependentTestMethods">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testNGPractice.DependentTestMethods@480bdb19]" name="setUp" is-config="true" duration-ms="6" started-at="2018-02-12T23:51:32Z" finished-at="2018-02-12T23:51:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testMethod2()[pri:0, instance:testNGPractice.DependentTestMethods@480bdb19]" name="testMethod2" duration-ms="5" started-at="2018-02-12T23:51:32Z" finished-at="2018-02-12T23:51:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at testNGPractice.DependentTestMethods.testMethod2(DependentTestMethods.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method status="PASS" signature="testMethod4()[pri:0, instance:testNGPractice.DependentTestMethods@480bdb19]" name="testMethod4" duration-ms="1" started-at="2018-02-12T23:51:33Z" finished-at="2018-02-12T23:51:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod4 -->
        <test-method status="PASS" signature="testMethod1()[pri:0, instance:testNGPractice.DependentTestMethods@480bdb19]" name="testMethod1" duration-ms="1" started-at="2018-02-12T23:51:33Z" depends-on-methods="testNGPractice.DependentTestMethods.testMethod2" finished-at="2018-02-12T23:51:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="PASS" signature="testMethod3()[pri:0, instance:testNGPractice.DependentTestMethods@480bdb19]" name="testMethod3" duration-ms="1" started-at="2018-02-12T23:51:33Z" depends-on-methods="testNGPractice.DependentTestMethods.testMethod1" finished-at="2018-02-12T23:51:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:testNGPractice.DependentTestMethods@480bdb19]" name="cleanUp" is-config="true" duration-ms="0" started-at="2018-02-12T23:51:33Z" finished-at="2018-02-12T23:51:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- testNGPractice.DependentTestMethods -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
